//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public int Start_time { get; set; }
        public int End_time { get; set; }
    }
}
